TAVILY_API_KEY="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"
MISTRAL_API_KEY="xl6G8H5wD0q0x8Xt0f2e5sYTUEFN4hS6"
SUPABASE_URL="https://edagmbhuswnrsvtcdsmd.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkYWdtYmh1c3ducnN2dGNkc21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NDIzMjAsImV4cCI6MjA5NDMxODMyMH0.VfmfRI4mctrlM-mQBNqlMIYxmcK6od7tqxpLgpPNx8k"